# Generated by Django 5.1.5 on 2025-02-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AidProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('aid_type', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('UNDERGRADUATE', 'Undergraduate'), ('POSTGRADUATE', 'Postgraduate')], max_length=20)),
                ('locality', models.CharField(choices=[('LOCAL', 'Local'), ('INTERNATIONAL', 'International')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], default='OPEN', max_length=10)),
                ('closing_date', models.DateField()),
            ],
        ),
    ]
