# Generated by Django 5.1.5 on 2025-02-08 15:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('last_update', models.DateField(default=django.utils.timezone.now)),
                ('aid_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.aidprogram')),
            ],
        ),
        migrations.CreateModel(
            name='AppealStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_reason', models.TextField()),
                ('appeal_date', models.DateField(default=django.utils.timezone.now)),
                ('appeal_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.applicationstatus')),
            ],
        ),
    ]
