# Generated by Django 5.1.2 on 2025-02-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_feedback_reply_alter_feedback_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='reply',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='feedback_attachments/'),
        ),
    ]
