# Generated by Django 5.1.5 on 2025-02-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_applicationstatus_appealstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidprogram',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
