# Generated by Django 5.1.5 on 2025-02-09 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_aidprogram_eligibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aidprogram',
            name='required_documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aidprogram',
            name='total_funds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='aid_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='allocated_funds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='officer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('additional_info', 'Additional Info Required'), ('submitted_to_funder', 'Submitted to Funder')], default='pending', max_length=20),
        ),
    ]
