# Generated by Django 5.1.5 on 2025-02-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_aidprogram_required_documents_aidprogram_total_funds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidprogram',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OPEN', 'Open'), ('CLOSE', 'Close')], default='PROPOSED', max_length=10),
        ),
    ]
