# Generated by Django 5.1.5 on 2025-02-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_aidprogram_approval_status_aidprogram_proposed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidprogram',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUBMIT TO FUNDERS', 'Sumit to Funders')], default='PENDING', max_length=20),
        ),
    ]
