# Generated by Django 5.1.5 on 2025-02-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_alter_aidprogram_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidprogram',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUBMIT TO FUNDERS', 'Submit to Funders')], default='PENDING', max_length=20),
        ),
    ]
