# Generated by Django 5.1.5 on 2025-02-11 00:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_alter_aidprogram_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundUtilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TUITION', 'Tuition'), ('LIVING', 'Living Expenses'), ('BOOKS', 'Books'), ('RESEARCH', 'Research'), ('OTHER', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('flagged', models.BooleanField(default=False)),
                ('acknowledged_by_funder', models.BooleanField(default=False)),
                ('aid_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.aidprogram')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aid_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.aidprogram')),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
