# Generated by Django 5.1.6 on 2025-02-11 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_fundutilization_impactreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImpactReport',
        ),
    ]
