# Generated by Django 5.1.2 on 2025-02-08 04:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_adminlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminLog',
            new_name='SystemLog',
        ),
    ]
