# Generated by Django 5.1.2 on 2025-02-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_adminlog_systemlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='action_type',
            field=models.CharField(choices=[('profile_update', 'Profile Update'), ('feedback_submission', 'Feedback Submission'), ('notification_sent', 'Notification Sent'), ('user_registration', 'User Registration'), ('user_login', 'User Login'), ('other', 'Other')], max_length=20),
        ),
    ]
